export interface CustomSpell {
    name: string;
    level: string;
    class: Class;
    casttime: Casttime;
    range: string;
    target: string;
    area: string;
    effect: string;
    duration: string;
    save: string;
    resist: Resist;
    dc: string;
    casterlevel: string;
    componenttext: Componenttext;
    schooltext: string;
    subschooltext: Subschooltext;
    descriptortext: string;
    savetext: string;
    resisttext: Resisttext;
    spontaneous: Resist;
    description: string;
    spellcomp?: SpellcompElement[] | Componenttext;
    spellschool?: SpellschoolElement[] | SpellschoolElement;
    spellsubschool?: Subschooltext[] | Subschooltext;
    spelldescript?: SpelldescriptElement[] | SpelldescriptElement;
    useradded?: Resist;
}

export enum Casttime {
    Ct2Min = 'ct2Min',
    Empty = '',
    SeeText = 'see text',
    The10Minutes = '10 minutes',
    The10MinutesOrMoreSeeText = '10 minutes or more; see text',
    The12Hours = '12 hours',
    The1Action = '1 action',
    The1ActionOr1MinuteSeeText = '1 action or 1 minute (see text)',
    The1Day = '1 day',
    The1FullRoundAction = '1 full-round action',
    The1Hour = '1 hour',
    The1Hour12Hours = '1 hour, 12 hours',
    The1ImmediateAction = '1 immediate action',
    The1Minute = '1 minute',
    The1MinutePerPage = '1 minute per page',
    The1Round = '1 round',
    The1RoundOr4HoursSeeText = '1 round or 4 hours; see text',
    The1SwiftAction = '1 swift action',
    The1SwiftActionOrImmediateActionSeeText = '1 swift action or immediate action; see text',
    The1Week = '1 week',
    The20Minutes = '20 minutes',
    The24Hours = '24 hours',
    The2Actions = '2 actions',
    The2Hours = '2 hours',
    The2Rounds = '2 rounds',
    The30Minutes = '30 minutes',
    The3Rounds = '3 rounds',
    The4Hours = '4 hours',
    The4Minutes = '4 minutes',
    The5Minutes = '5 minutes',
    The6Hours = '6 hours',
    The6Rounds = '6 rounds',
    The8Hours = '8 hours',
    The9Days = '9 days',
}

export enum Class {
    Hunter = 'Hunter',
    Oracle = 'Oracle',
    Sorcerer = 'Sorcerer',
}

export enum Componenttext {
    Empty = '',
    Material = 'Material',
    MaterialOrDivineFocus = 'Material or Divine Focus',
    Somatic = 'Somatic',
    SomaticDivineFocus = 'Somatic, Divine Focus',
    SomaticFocus = 'Somatic, Focus',
    SomaticMaterial = 'Somatic, Material',
    SomaticMaterialDivineFocus = 'Somatic, Material, Divine Focus',
    SomaticMaterialFocus = 'Somatic, Material, Focus',
    SomaticMaterialOrDivineFocus = 'Somatic, Material or Divine Focus',
    ThoughtSomaticMaterial = 'Thought, Somatic, Material',
    VOrS = 'V or S',
    Verbal = 'Verbal',
    VerbalDivineFocus = 'Verbal, Divine Focus',
    VerbalFocus = 'Verbal, Focus',
    VerbalFocusOrDivineFocus = 'Verbal, Focus or Divine Focus',
    VerbalMaterial = 'Verbal, Material',
    VerbalMaterialOrDivineFocus = 'Verbal, Material or Divine Focus',
    VerbalSomatic = 'Verbal, Somatic',
    VerbalSomaticDivineFocus = 'Verbal, Somatic, Divine Focus',
    VerbalSomaticFocus = 'Verbal, Somatic, Focus',
    VerbalSomaticFocusDivineFocus = 'Verbal, Somatic, Focus, Divine Focus',
    VerbalSomaticFocusMaterialOrDivineFocus = 'Verbal, Somatic, Focus, Material or Divine Focus',
    VerbalSomaticFocusOrDivineFocus = 'Verbal, Somatic, Focus or Divine Focus',
    VerbalSomaticFocusSeeText = 'Verbal, Somatic, Focus, See Text',
    VerbalSomaticMaterial = 'Verbal, Somatic, Material',
    VerbalSomaticMaterialDivineFocus = 'Verbal, Somatic, Material, Divine Focus',
    VerbalSomaticMaterialDivineFocusSeeText = 'Verbal, Somatic, Material, Divine Focus, See Text',
    VerbalSomaticMaterialDivineFocusXPCost = 'Verbal, Somatic, Material, Divine Focus, XP Cost',
    VerbalSomaticMaterialFocus = 'Verbal, Somatic, Material, Focus',
    VerbalSomaticMaterialFocusDivineFocus = 'Verbal, Somatic, Material, Focus, Divine Focus',
    VerbalSomaticMaterialFocusXPCost = 'Verbal, Somatic, Material, Focus, XP Cost',
    VerbalSomaticMaterialMaterialOrDivineFocus = 'Verbal, Somatic, Material, Material or Divine Focus',
    VerbalSomaticMaterialOrDivineFocus = 'Verbal, Somatic, Material or Divine Focus',
    VerbalSomaticMaterialOrDivineFocusSeeText = 'Verbal, Somatic, Material or Divine Focus, See Text',
    VerbalSomaticMaterialSeeText = 'Verbal, Somatic, Material, See Text',
    VerbalSomaticMaterialXPCost = 'Verbal, Somatic, Material, XP Cost',
    VerbalSomaticSeeText = 'Verbal, Somatic, See Text',
    VerbalSomaticXPCost = 'Verbal, Somatic, XP Cost',
}

export enum Resist {
    Empty = '',
    NO = 'nO',
    No = 'no',
    NoAndYesHarmless = 'no and yes (harmless)',
    NoAndYesObject = 'no and yes (object)',
    NoAndYesSeeText = 'no and Yes; see text',
    NoHarmless = 'no (harmless)',
    NoHarmlessSeeText = 'no (harmless, see text)',
    NoObject = 'no (object)',
    NoObjectAndYesSeeText = 'no (object) and yes (see text)',
    NoObjectSeeText = 'no (object); see text',
    NoOrYesHarmless = 'no or yes (harmless)',
    NoOrYesHarmlessObject = 'no or yes (harmless, object)',
    NoOrYesObject = 'no or yes (object)',
    NoSeeText = 'no; see text',
    NoSpecialSeeBelow = 'no (special, see below)',
    None = 'none',
    NoneObject = 'none (object)',
    PurpleNoAndYesSeeText = 'no and yes (see text)',
    PurpleNoObjectAndYesSeeText = 'no (object) and Yes; see text',
    PurpleNoSeeText = 'no (see text)',
    PurpleYesHarmlessObject = 'yes (Harmless, Object)',
    PurpleYesHarmlessSeeText = 'yes (harmless) (see text)',
    PurpleYesObjectSeeText = 'yes (object), see text',
    PurpleYesSeeText = 'yes, see text',
    Resist = '-',
    ResistNo = 'no.',
    ResistNoAndYesObject = 'no and Yes (object)',
    ResistNoAndYesSeeText = 'no and yes; see text',
    ResistNoObjectAndYesSeeText = 'no (object) and yes; see text',
    ResistNoSeeText = 'no, see text',
    ResistSeeText = 'see Text',
    ResistSeeTextSeeText = 'seeText; see text',
    ResistSpecialSeeText = 'special, see text',
    ResistYesHarmless = 'yes (Harmless)',
    ResistYesHarmlessObject = 'yes (harmless/object)',
    ResistYesHarmlessOrYesSeeText = 'yes (harmless) or yes, see text',
    ResistYesHarmlessSeeText = 'yes (harmless; see text)',
    ResistYesObjectSeeText = 'yes (object) (see text)',
    ResistYesOrNoObject = 'yes or No (object)',
    ResistYesSeeText = 'yes; see text',
    SeeText = 'see text',
    SeeTextSeeText = 'see Text; see text',
    Special = 'special',
    SpecialSeeText = 'special; see text',
    Yes = 'yes',
    YesDevoursItsOriginal = 'yes (devours its original)',
    YesForTarget = 'yes (for target)',
    YesHarmless = 'yes (harmless)',
    YesHarmlessAndSeeText = 'yes (harmless) and see text',
    YesHarmlessObject = 'yes (harmless, object)',
    YesHarmlessObjectSeeText = 'yes (harmless, object), see text',
    YesHarmlessOrNo = 'yes (harmless) or no',
    YesHarmlessOrYesHarmlessObject = 'yes (harmless) or yes (harmless, object)',
    YesHarmlessOrYesSeeText = 'yes (harmless) or yes; see text',
    YesHarmlessSeeText = 'yes (harmless); see text',
    YesObject = 'yes (object)',
    YesObjectAndSeeText = 'yes (object), and see text',
    YesObjectHarmless = 'yes (object, harmless)',
    YesObjectOrYesSeeText = 'yes (object) or yes; see text',
    YesObjectSeeText = 'yes (object); see text',
    YesObjectThenYesSeeText = 'yes (object), then yes (see text)',
    YesOrNoObject = 'yes or no (object)',
    YesOrNoSeeText = 'yes or no; see text',
    YesSeeBelow = 'yes (see below)',
    YesSeeText = 'yes (see text)',
    YesSeeTextOrNoObject = 'yes; see text or no (object)',
}

export enum Resisttext {
    Empty = '',
    HarmlessNo = 'Harmless, No',
    HarmlessNoSeeText = 'Harmless, No, See Text',
    HarmlessNoSeeTextYes = 'Harmless, No, See Text, Yes',
    HarmlessNoYes = 'Harmless, No, Yes',
    HarmlessObjectSeeTextYes = 'Harmless, Object, See Text, Yes',
    HarmlessObjectYes = 'Harmless, Object, Yes',
    HarmlessSeeTextYes = 'Harmless, See Text, Yes',
    HarmlessYes = 'Harmless, Yes',
    No = 'No',
    NoObject = 'No, Object',
    NoObjectSeeText = 'No, Object, See Text',
    NoObjectSeeTextYes = 'No, Object, See Text, Yes',
    NoObjectYes = 'No, Object, Yes',
    NoSeeText = 'No, See Text',
    NoSeeTextSpecial = 'No, See Text, Special',
    NoSeeTextYes = 'No, See Text, Yes',
    ObjectSeeTextYes = 'Object, See Text, Yes',
    ObjectYes = 'Object, Yes',
    SeeText = 'See Text',
    SeeTextSpecial = 'See Text, Special',
    SeeTextYes = 'See Text, Yes',
    Special = 'Special',
    Yes = 'Yes',
}

export enum SpellcompElement {
    DivineFocus = 'Divine Focus',
    Focus = 'Focus',
    FocusOrDivineFocus = 'Focus or Divine Focus',
    Material = 'Material',
    MaterialOrDivineFocus = 'Material or Divine Focus',
    SeeText = 'See Text',
    Somatic = 'Somatic',
    Thought = 'Thought',
    Verbal = 'Verbal',
    XPCost = 'XP Cost',
}

export enum SpelldescriptElement {
    Acid = 'Acid',
    Air = 'Air',
    Chaotic = 'Chaotic',
    Cold = 'Cold',
    Compulsion = 'Compulsion',
    Curse = 'Curse',
    Darkness = 'Darkness',
    Death = 'Death',
    Disease = 'Disease',
    Earth = 'Earth',
    Electricity = 'Electricity',
    Emotion = 'Emotion',
    Evil = 'Evil',
    Fear = 'Fear',
    Fire = 'Fire',
    Force = 'Force',
    Good = 'Good',
    Ink = 'Ink',
    LanguageDependent = 'Language-Dependent',
    Lawful = 'Lawful',
    Light = 'Light',
    MindAffecting = 'Mind-Affecting',
    Mythos = 'Mythos',
    Pain = 'Pain',
    Poison = 'Poison',
    Psionic = 'Psionic',
    Ruse = 'Ruse',
    SeeText = 'See text',
    Shadow = 'Shadow',
    Sonic = 'Sonic',
    SpelldescriptSeeText = 'See Text',
    Temporal = 'Temporal',
    Water = 'Water',
}

export enum SpellschoolElement {
    Abjuration = 'Abjuration',
    AetherElemental = 'Aether Elemental',
    AirElemental = 'Air Elemental',
    AllElements = 'All Elements',
    Clockwork = 'Clockwork',
    Conjuration = 'Conjuration',
    Divination = 'Divination',
    EarthElemental = 'Earth Elemental',
    Enchantment = 'Enchantment',
    Evocation = 'Evocation',
    FireElemental = 'Fire Elemental',
    Illumination = 'Illumination',
    Illusion = 'Illusion',
    InkMagic = 'Ink Magic',
    MetalElemental = 'Metal Elemental',
    Necromancy = 'Necromancy',
    Transmutation = 'Transmutation',
    Universal = 'Universal',
    VoidElemental = 'Void Elemental',
    WaterElemental = 'Water Elemental',
    WoodElemental = 'Wood Elemental',
}

export enum Subschooltext {
    Air = 'Air',
    AirFire = 'Air, Fire',
    Animation = 'Animation',
    AnimationNecrophagy = 'Animation, Necrophagy',
    Calling = 'Calling',
    CallingCreation = 'Calling, Creation',
    Charm = 'Charm',
    CharmNecrophagy = 'Charm, Necrophagy',
    Cold = 'Cold',
    Compulsion = 'Compulsion',
    CompulsionCurse = 'Compulsion, Curse',
    CompulsionLanguageDependentMindAffecting = 'Compulsion, Language-Dependent, Mind-Affecting',
    CompulsionMindAffecting = 'Compulsion, Mind-Affecting',
    CompulsionNecrophagy = 'Compulsion, Necrophagy',
    Creation = 'Creation',
    CreationLight = 'Creation, Light',
    CreationOrCalling = 'Creation or Calling',
    CreationSeeTextSummoning = 'Creation, See text, Summoning',
    CreationShadowflesh = 'Creation, Shadowflesh',
    CreationSummoning = 'Creation, Summoning',
    CreationTeleportation = 'Creation, Teleportation',
    Curse = 'Curse',
    Darkness = 'Darkness',
    DarknessShadowTKPIllumin = 'Darkness, Shadow, tKPIllumin',
    Death = 'Death',
    Dimensional = 'Dimensional',
    DimensionalTeleportation = 'Dimensional, Teleportation',
    Earth = 'Earth',
    EarthFire = 'Earth, Fire',
    Electric = 'Electric',
    Emotion = 'Emotion',
    Empty = '',
    Evil = 'Evil',
    EvilLawfulSummoning = 'Evil, Lawful, Summoning',
    EvilShadow = 'Evil, Shadow',
    Figment = 'Figment',
    FigmentGlamer = 'Figment, Glamer',
    FigmentGlamerShadow = 'Figment, Glamer, Shadow',
    Fire = 'Fire',
    Force = 'Force',
    Glamer = 'Glamer',
    GlamerShadow = 'Glamer, Shadow',
    GlamerSummoning = 'Glamer, Summoning',
    Good = 'Good',
    GoodLight = 'Good, Light',
    Grief = 'Grief',
    GriefMindAffecting = 'Grief, Mind-Affecting',
    Healing = 'Healing',
    LanguageDependent = 'Language-Dependent',
    Lawful = 'Lawful',
    Light = 'Light',
    MindAffecting = 'Mind-Affecting',
    Necrophagy = 'Necrophagy',
    None = 'None',
    Ooze = 'Ooze',
    OozePolymorph = 'Ooze, Polymorph',
    Pattern = 'Pattern',
    Phantasm = 'Phantasm',
    Polymorph = 'Polymorph',
    PolymorphSeeText = 'Polymorph, See text',
    Scrying = 'Scrying',
    SeeText = 'See text',
    Shadow = 'Shadow',
    ShadowShadowflesh = 'Shadow, Shadowflesh',
    ShadowTeleportation = 'Shadow, Teleportation',
    Shadowflesh = 'Shadowflesh',
    Sonic = 'Sonic',
    Special = 'Special',
    Summoning = 'Summoning',
    TKPClockwo = 'tKPClockwo',
    TKPIllumin = 'tKPIllumin',
    Teleportation = 'Teleportation',
}
